spring:
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:spring_security_demo_db
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
#    initializationMode: ALWAYS
#    schema: classpath:schema.sql
#    data:
#      - classpath:data.sql
  flyway:
    # 是否启用flyway
    enabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      # 使用内嵌数据库（h2db的内存模式）时，默认值为create，create模式报错，所以手动设置为none
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

logging:
  file:
    name: logs/app.log
  level:
    org.springframework.security: debug
server:
  port: 8080